### ISSUE TITLE
there is no [isOff]?

### ISSUE THREAD

**Issue by mohamedebrahim96** [aminebenkeroum/toggle-switch-react-native#1]
hi, guys how can I make a statement when it's off ??
------------------------

![wqeqweqwe](https://user-images.githubusercontent.com/16405013/35139935-f28a049a-fcfd-11e7-8773-9e0576f7213e.JPG)

**Comment by aminebenkeroum** [comment]
@mohamedebrahim96  Actually the parameter "isOn" returns false or true depending on the toggle state, you can check it and do the peace of code you want to do on each state.

**Comment by mohamedebrahim96** [comment]
@aminebenkeroum 
please give me small code...how to make the value to label whether true or false.
------------------------------------------



![aerwerwer](https://user-images.githubusercontent.com/16405013/35181952-3c37c394-fdd4-11e7-863c-51bb4cd3acc4.JPG)

**Comment by mohamedebrahim96** [comment]
ok thanks, i've solved the problem
