### ISSUE TITLE
How to change the width ?

### ISSUE THREAD

**Issue by JayKurniawan** [aminebenkeroum/toggle-switch-react-native#11]

**Comment by mun5865** [comment]
You can customize your toggle switch in`ToggleSwitch.js`
You just have to change the styles of your chosen toggle switch type(small/large/default).
`  static calculateDimensions(size) {
    switch (size) {
      case 'small':
        return ({
          width: 50, padding: 10, circleWidth: 15, circleHeight: 15, translateX: 22,
        });
      case 'large':
        return ({
          width: 100, padding: 20, circleWidth: 30, circleHeight: 30, translateX: 38,
        });
      default:
        return ({
          width: 45, padding: 12, circleWidth: 18, circleHeight: 18, translateX: 26,
        });
    }
  }`
