### ISSUE TITLE
cannot add a child that doesn't have a yoga node to a parent ....

### ISSUE THREAD

**Issue by medelvann** [aminebenkeroum/toggle-switch-react-native#13]
in IOS everything is ok but Android error in react native 0.56    
 <ToggleSwitch

                            label="Hello"
                            isOn={true}
                            onColor={colors.colorDarkGreen}
                            offColor={colors.colorGray_v9}
                            size='small'

                            onToggle={(text) => this.onChangeGlobalSwitch(text)}

                        />;]

![screenshot_1538297636](https://user-images.githubusercontent.com/35561726/46255604-d104bb00-c4ab-11e8-8c35-70bf5e41f168.png)

**Comment by Proyoyo** [comment]
@medelvann Remove the ;] at the end of your code.
