### ISSUE TITLE
unable to toggle the switch.

### ISSUE THREAD

**Issue by ali373** [aminebenkeroum/toggle-switch-react-native#48]
The switch does not toggle.
<img width="719" alt="Screenshot 2021-05-20 at 12 26 37 PM" src="https://user-images.githubusercontent.com/43233646/118937253-c2be8280-b966-11eb-94b2-7da7b2d181c4.png">

**Comment by peterchibunna** [comment]
You have to assign `isOn` to a state value and then modify this state value in the `onToggle`

```
const [isSelected, setSelected] = useState(false);
...
<ToggleSwitch
 isOn={isSelected}
 ...
 onToggle={isOn=> setSelected(isOn)}
/>

```
