### ISSUE TITLE
Support hitSlop props

### ISSUE THREAD

**Issue by chungweileong94** [aminebenkeroum/toggle-switch-react-native#54]
Sometimes the hit area is too small to tap on, it will be good if we can have a prop to control the `hitSlop`.

**Comment by ariangel** [comment]
@aminebenkeroum can you create a new version with this change?

**Comment by chungweileong94** [comment]
@ariangel The npm package for this is lagging behind a lot, if you really need it, I would suggest you install it directly from this repo.

```
yarn add https://github.com/aminebenkeroum/toggle-switch-react-native.git
```

**Comment by aminebenkeroum** [comment]
New version released
