### ISSUE TITLE
Issue with ios app

### ISSUE THREAD

**Issue by dwivediamit** [aminebenkeroum/toggle-switch-react-native#7]
Hi, 
Can you help here.
Toggle-switch-react-native is working fine for android but in ios it is not working it,s not getting on please help...
Will it work for ios or only for android.

**Comment by og24715** [comment]
Hmm, as far as I have seen that it is works for me on iOS and Android both.
Actually you can check this repo's sample gif. this is correctly working on iOS. 

Maybe, npm version has not been Bump. Please try install toggle-switch-react-native from this repo not npm.
